use('names')

// db.hostInfo()
// db.getName()
// db.getMongo()
// db.currentOp()
// db.dropDatabase()
// db.getCollectionInfos()
// db.getCollectionNames()
// db.getLastError()
// db.getLastErrorObj()
// db.isMaster()
// db.getReplicationInfo()
// db.listCommands()
// db.logout()
// db.printCollectionStats()
// db.serverBuildInfo()
// db.serverStatus()
// db.shutdownServer()
// db.stats()
// db.version()
// db.createCollection("DemoXYZ")
db.DemoXYZ.drop()